### PR TITLE
Remove duplicated libraries and add the UPB library

### PR DESCRIPTION
**Pull request by kevswims**
With these changes we are able to build and run our library using the 1.26 version of gRPC.

The duplicate grpc libraries was causing the following error in the CMake:
```    -- Library grpc++ found /home/kelannen/.conan/data/grpc/1.26.0/kevin/testing/package/491e190cb39b1a21779584cb6f2e67fb2b1d8aab/lib/libgrpc++.a
    CMake Error at build/conanbuildinfo.cmake:1137 (add_library):
      add_library cannot create imported target "CONAN_LIB::grpc_grpc++" because
      another target with the same name already exists.
    Call Stack (most recent call first):
      build/conanbuildinfo.cmake:615 (conan_package_library_targets)
      build/conanbuildinfo.cmake:1019 (conan_define_targets)
      CMakeLists.txt:10 (conan_basic_setup)


    -- Library grpc_unsecure found /home/kelannen/.conan/data/grpc/1.26.0/kevin/testing/package/491e190cb39b1a21779584cb6f2e67fb2b1d8aab/lib/libgrpc_unsecure.a
    -- Library grpc_plugin_support found /home/kelannen/.conan/data/grpc/1.26.0/kevin/testing/package/491e190cb39b1a21779584cb6f2e67fb2b1d8aab/lib/libgrpc_plugin_support.a
    -- Library grpc_cronet found /home/kelannen/.conan/data/grpc/1.26.0/kevin/testing/package/491e190cb39b1a21779584cb6f2e67fb2b1d8aab/lib/libgrpc_cronet.a
    -- Library grpcpp_channelz found /home/kelannen/.conan/data/grpc/1.26.0/kevin/testing/package/491e190cb39b1a21779584cb6f2e67fb2b1d8aab/lib/libgrpcpp_channelz.a
    -- Library grpc found /home/kelannen/.conan/data/grpc/1.26.0/kevin/testing/package/491e190cb39b1a21779584cb6f2e67fb2b1d8aab/lib/libgrpc.a
    CMake Error at build/conanbuildinfo.cmake:1137 (add_library):
      add_library cannot create imported target "CONAN_LIB::grpc_grpc" because
      another target with the same name already exists.
    Call Stack (most recent call first):
      build/conanbuildinfo.cmake:615 (conan_package_library_targets)
      build/conanbuildinfo.cmake:1019 (conan_define_targets)
      CMakeLists.txt:10 (conan_basic_setup)```

Our library was also having an issue at the final linking stage without the UPB library so I have added it in as well.

### CODE REVIEW

**Comment by Croydon** [comment]
Thanks for pointing out this issue!

**Comment by kevswims** [comment]
Thanks, @Croydon for getting this fixed.

In the future I would prefer if my PR was merged or feedback was given for why it could not be merged instead of reauthoring the commits in your name. I am always happy to rebase or tweak a commit if it is needed.

Thanks,
Kevin

**Comment by Croydon** [comment]
@kevswims You are right, sorry. I should have at least added you as a co-author

Main reason was that I merged first #29. I think that the order of the linking makes more sense there. And since I only checked the change summary of your pull request, I didn't realize that I could cherry-pick a8683dd separately.

Since I didn't merge it in any stable branch yet, I have rewritten this with a push force

https://github.com/inexorgame/conan-grpc/commit/a486769ddab127226d819f74de00facbb77f264a

**Comment by kevswims** [comment]
Great! Thanks @Croydon

**Pull request closed without merging**
