### PR TITLE
Add libstdc++11 support

### PR DESCRIPTION
**Pull request by canmor**
Add libcxx=libstdc++11 for gcc

### CODE REVIEW

**Comment by canmor** [comment]
Please accept to include `libstdc++11` support.

You could check doc here: https://github.com/conan-io/conan-package-tools
> pure_c: (Default True) If your project is C++, pass the pure_c=False to add both combinations using libstdc and libstdc++11 for the setting compiler.libcxx. When True, the default profile value of libcxx will be applied. If you don't want libcxx value to apply to your binary packages you have to use the configure method to remove it:
    def configure(self):
        del self.settings.compiler.libcxx

**Review by Croydon — APPROVED** [review]
Thanks!

**Comment by canmor** [comment]
Just curious, seams CI failed because of c-ares/1.15.0@conan/stable missing GCC9 and Clang 11 binaries, I found that you have already open an issue in conan-center-index, and it was declared been solved, but at least not for c-ares, shall we open another issue to push that?

**Comment by canmor** [comment]
I finally understand that `c-ares/1.15.0@conan/stable` goes to `c-ares/1.15.0`, therefore, I open a new pr: #36

**Pull request merged**
