### PR TITLE
Add components and extra options

### PR DESCRIPTION
**Pull request by Hopobcn**
@Croydon please consider this PR

I've been trying to add components for a while, now that CCI is about to have protobuf/3.12 I think it's the moment to release the kraken xd.

Hope it's an improvement. (not feature complete)

PD: tested locally with CCI protobuf/3.12.4 I guess compilation will fail until it's available on CCI

### CODE REVIEW

**Comment by Croydon** [comment]
Regarding components support, I hope you did not start from scratch 🙈 

I have a draft in the git history which I reverted for the time being

https://github.com/inexorgame/conan-grpc/commit/7d066863367781c7c20c16cdcacbe41efb429c59

👍 for the build options

**Comment by Hopobcn** [comment]
> Regarding components support, I hope you did not start from scratch 🙈
> 
> I have a draft in the git history which I reverted for the time being
> 
> [7d06686](https://github.com/inexorgame/conan-grpc/commit/7d066863367781c7c20c16cdcacbe41efb429c59)
> 
> 👍 for the build options

Yes, I started from scratch 🙈 (mainly I looked at upstream main CMakeLists.txt searching all `add_libraries` + looking at pkgconfig data). I started with an approach like cci-abseil does (trying to auto-deduce components from cmake files) but it was confusing and didn't actually knew what I was generating.. so I went full manual approach xd.

Once protobuf is in CCI I'll try to check 7d06686 and see if it differs from what I have.

**Comment by Hopobcn** [comment]
* MinGW 7 fails with:

> The 're2/20201001' package has 'exports_sources' but sources not found in local cache.
Probably it was installed from a remote that is no longer available.

* All gcc/clang with:

> conans.errors.InvalidNameException: Specify the 'user' and the 'channel' or neither of them

**Comment by Hopobcn** [comment]
Travis failed with "The job exceeded the maximum log length, and has been terminated."  Compiler verbosity should be reduced (or maybe redirecting output to a file)

**Comment by Croydon** [comment]
I have split the Travis build jobs by into `Debug`, `Release`. Maybe that is enough. However, you have added CMake verbosity in this PR which is in general the problem, not sure if you have used that for debugging..? ac671beea316884122d7e21f31756fbdbdcddfc2

I have updated the recipe to version 1.31.1 8768b2d8e1f9238095c2e55e65c6296563480eda
Newer versions should probably use Protobuf >= 3.13.0 (https://github.com/conan-io/conan-center-index/pull/3583)

I have merged and adapted a little bit the new build options for the grpc plugins: 4a46615d58077a00d6a0cb9086f914b5059ebabc I have added you as a co-author in the commit to give you credits for this :) 

I'm sorry for the CI troubles. I think you have just discovered a bug in the Bincrafters tooling (which is used here too). You might want to create a new pull request based on and targeting the branch `testing/1.13.1`. I will have a look what to do about the CI bug 🤔

**Comment by Hopobcn** [comment]
Ohhhh I forgot I added `cmake.verbose = True` :-( 

 I'll close this PR and open a new one with the components changes based on 1.31.1.

Regarding ci problems, I think that `Specify the 'user' and the 'channel' or neither of them` issue is related to this https://github.com/conan-io/conan-package-tools/issues/479 (there's a fix here https://github.com/conan-io/conan-package-tools/pull/482) but it's weird that only happens on this PR but not on commits directly done on on master.

**Comment by Croydon** [comment]
The pushes itself have the values of `CONAN_USERNAME` and `CONAN_LOGIN_USERNAME`, but as they are GitHub Actions "secrets" they are not available to outside pull request. I could temporary fork the CI config files I think, but in the long term it needs an actual solution

**Pull request closed without merging**
