### PR TITLE
Split in hybrid default+installer

### PR DESCRIPTION
**Pull request by KristianJerpetjon**
I tried using the FindPackage(gRPC) but that adds -lprotoc and -lprotobuf which fail. However with all the libs included i was able to build the basic example with some modifications.. However i would prefer to be able to use each lib specifically instead of CONAN_PKG::grpc 

I added the gRPCModule.cmake  which includes the wrapper around the grpc as in https://github.com/IvanSafonov/grpc-cmake-example however some modifications where needed to make it work. Adjusted the test package accordingly

### CODE REVIEW

**Comment by KristianJerpetjon** [comment]
@Croydon this one is now green any comments ? I have already run into the issue of the "codegen" beeing attempted to be build't for target in a cross compile environment.. and i really would like to make a grpc_codegen package alongside this recipe like protoc_installer to solve that issue.

**Comment by Croydon** [comment]
I'm not really comfortable with adding even more custom CMake module code while we are trying to get rid of these things step-by-step

I guess I would also like to wait until protoc is in CCI. This alone caused quite some questions which aren't answered yet

If you want you can make another pull request in the meantime for just adding the missing libraries

**Comment by KristianJerpetjon** [comment]
@Croydon so i shouldn't use the protoc approach for the binaries ?
The grpc_generate_cpp is in the CMakeLists.txt of the main project i agree we shoudln't do to much custom. I have also noticed that this package doesn't really work as it is for cross compiling. Although they have added some support for it you loose grpc++reflection when crosscompiling. For that reason i started looking at doing the same as prococ_installer please let me know if that is not the way to go to get the grpc_cpp_plugin working when crosscompiling

**Comment by KristianJerpetjon** [comment]
@Croydon 
I am considering if maybe going for [this](https://github.com/KristianJerpetjon/conan-grpc/tree/kristian) branch is better  ? This works for cross compiling and codegen

**Comment by KristianJerpetjon** [comment]
@Croydon updated to re written version with grpc_installer.. this one also works for cross compilation

**Review by Croydon — CHANGES_REQUESTED** [review]
Conan is working on a new cross-compile approach which won't make this kind of split required anymore

Parts of it shipped in 1.24.0 already

**Comment by KristianJerpetjon** [comment]
I can try looking at it

tor. 23. apr. 2020, 15:54 skrev Croydon <notifications@github.com>:

**Pull request closed without merging**
